<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Child_parent extends Model {
    use Traits\Child_parentTrait;
    protected static $tableName = 'child_parent';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'child_id' => 'INTEGER',
        'parent_id' => 'INTEGER',
        'created_at' => 'INTEGER',
        'updated_at' => 'INTEGER',
        'deleated_at' => 'INTEGER',
    ];

	public function get_parent() {
		return $this->belongsTo('note', 'parent_id');
	}
	public function get_child() {
		return $this->belongsTo('note', 'child_id');
	}
}