<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Comment extends Model {
    use Traits\CommentTrait;
    protected static $tableName = 'comment';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'note_id' => 'INTEGER',
        'user_id' => 'INTEGER',
        'comment' => 'TEXT',
        'visible' => 'INTEGER',
        'moderated' => 'INTEGER',
        'created_at' => 'INTEGER',
        'updated_at' => 'INTEGER',
        'deleated_at' => 'INTEGER',
    ];

	public function get_note() {
		return $this->belongsTo('note', 'note_id');
	}
	public function get_user() {
		return $this->belongsTo('user', 'user_id');
	}
}