<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Note extends Model {
    use Traits\NoteTrait;
    protected static $tableName = 'note';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'user_id' => 'INTEGER',
        'type_id' => 'INTEGER',
        'title' => 'INTEGER',
        'details' => 'TEXT',
        'style' => 'INTEGER',
        'keywords' => 'INTEGER',
        'created_at' => 'INTEGER',
        'updated_at' => 'INTEGER',
        'deleated_at' => 'INTEGER',
    ];

	public function get_comment() {
		return $this->hasMany('comment', 'note_id');
	}
	public function get_user() {
		return $this->belongsToMany('user', 'user_id', 'comment', 'note_id');
	}
	public function get_type() {
		return $this->belongsTo('type', 'type_id');
	}
	public function get_note_checklist() {
		return $this->hasMany('note_checklist', 'note_id');
	}
	public function get_note_todo() {
		return $this->hasMany('note_todo', 'note_id');
	}
}