<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Note_checklist extends Model {
    use Traits\Note_checklistTrait;
    protected static $tableName = 'note_checklist';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'note_id' => 'INTEGER',
        'checked' => 'INTEGER',
        'checked_at' => 'TIMESTAMP',
        'created_at' => 'INTEGER',
        'updated_at' => 'INTEGER',
        'deleated_at' => 'INTEGER',
    ];

	public function get_note() {
		return $this->belongsTo('note', 'note_id');
	}
}