<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Note_todo extends Model {
    use Traits\Note_todoTrait;
    protected static $tableName = 'note_todo';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'note_id' => 'INTEGER',
        'priority' => 'INTEGER',
        'deadline' => 'TIMESTAMP',
        'reminder' => 'TIMESTAMP',
        'completion_status' => 'INTEGER',
        'completed_at' => 'TIMESTAMP',
        'recurrence' => 'TEXT',
        'created_at' => 'INTEGER',
        'updated_at' => 'INTEGER',
        'deleated_at' => 'INTEGER',
    ];

	public function get_note() {
		return $this->belongsTo('note', 'note_id');
	}
}