<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Oauth_provider extends Model {
    use Traits\Oauth_providerTrait;
    protected static $tableName = 'oauth_provider';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'name' => 'VARCHAR(100)',
        'client_id' => 'VARCHAR(255)',
        'client_secret' => 'VARCHAR(255)',
        'auth_url' => 'TEXT',
        'token_url' => 'TEXT',
        'scopes' => 'TEXT',
    ];


}