<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Profile extends Model {
    use Traits\ProfileTrait;
    protected static $tableName = 'profile';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'user_id' => 'INTEGER',
        'first_name' => 'VARCHAR(255)',
        'last_name' => 'VARCHAR(255)',
        'bio' => 'TEXT',
        'date_of_birth' => 'TIMESTAMP',
        'gender' => 'INTEGER',
        'address' => 'VARCHAR(255)',
        'phone_number' => 'VARCHAR(50)',
        'social_links' => 'TEXT',
        'image_url' => 'TEXT',
        'root_id' => 'INTEGER',
        'created_at' => 'TIMESTAMP',
        'updated_at' => 'TIMESTAMP',
        'deleted_at' => 'TIMESTAMP',
    ];

	public function get_root() {
		return $this->belongsTo('note', 'root_id');
	}
	public function get_user() {
		return $this->belongsTo('user', 'user_id');
	}
}