<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Refresh_token extends Model {
    use Traits\Refresh_tokenTrait;
    protected static $tableName = 'refresh_token';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'user_id' => 'INTEGER',
        'refresh_token' => 'TEXT',
        'expires_at' => 'TIMESTAMP',
        'created_at' => 'TIMESTAMP',
        'updated_at' => 'TIMESTAMP',
    ];

	public function get_user() {
		return $this->belongsTo('user', 'user_id');
	}
}