<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class Type extends Model {
    use Traits\TypeTrait;
    protected static $tableName = 'type';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'name' => 'VARCHAR(50)',
        'description' => 'TEXT',
        'created_at' => 'TIMESTAMP',
        'updated_at' => 'TIMESTAMP',
        'deleted_at' => 'TIMESTAMP',
    ];

	public function get_note() {
		return $this->hasMany('note', 'type_id');
	}
}