<?php
/**
 * This file was generated by RestInPeace.
 * Any changes made to this file will be overwritten when the schema is updated.
 * Use the corresponding trait file to add custom methods to this model.
 */
namespace RestInPeace\Models;
use RestInPeace\Model;
class User extends Model {
    use Traits\UserTrait;
    protected static $tableName = 'user';
    protected static $primaryKeys = ['id'];
    public static $_attributes = [
        'id' => 'INTEGER',
        'email' => 'VARCHAR(255)',
        'username' => 'VARCHAR(255)',
        'password_hash' => 'VARCHAR(255)',
        'oauth_provider' => 'VARCHAR(50)',
        'oauth_provider_user_id' => 'VARCHAR(255)',
        'created_at' => 'TIMESTAMP',
        'updated_at' => 'TIMESTAMP',
        'deleted_at' => 'TIMESTAMP',
    ];

	public function get_access_token() {
		return $this->hasMany('access_token', 'user_id');
	}
	public function get_comment() {
		return $this->hasMany('comment', 'user_id');
	}
	public function get_note() {
		return $this->belongsToMany('note', 'note_id', 'comment', 'user_id');
	}
	public function get_profile() {
		return $this->hasMany('profile', 'user_id');
	}
	public function get_refresh_token() {
		return $this->hasMany('refresh_token', 'user_id');
	}
}